name: Publish Rust Crates to crates.io

on:
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: "Deployment Environment"
        required: true
        default: "pre-prod"
        type: string

  release:
    types: [created]

jobs:
  publish:
    environment: ${{ github.event.inputs.deploy_environment }}
    name: publish
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Publish authly-core
        run: cargo publish --package authly-core

      - name: Publish authly-token
        run: cargo publish --package authly-token

      - name: Publish authly-session
        run: cargo publish --package authly-session

      - name: Publish authly-oidc
        run: cargo publish --package authly-oidc

      - name: Publish authly-flow
        run: cargo publish --package authly-flow

      - name: Publish authly-actix
        run: cargo publish --package authly-actix

      - name: Publish authly-axum
        run: cargo publish --package authly-axum

      - name: Publish authly-providers-discord
        run: cargo publish --package authly-providers-discord

      - name: Publish authly-providers-github
        run: cargo publish --package authly-providers-github

      - name: Publish authly-providers-google
        run: cargo publish --package authly-providers-google
